### ISSUE TITLE
ガウス混合モデルの結果の可視化の箇所において，サンプルプログラムに誤りがありました．

### ISSUE THREAD

**Issue by tom-uchida** [shimitaku/MachineLearning-Book#4]
第3章のガウス混合モデルによるクラスタリングの結果を可視化する際に，
サンプルプログラムをそのまま実行すると，書籍に載っている図のような色分けになりませんでした．
![Figure_1](https://user-images.githubusercontent.com/29174534/88181087-4cc78d00-cc69-11ea-935c-dfa640b15369.png)

おそらく，引数cに渡しているラベル配列の問題ではないかと思います．
`plt.scatter(X_norm[:, 0], X_norm[:, 1], c=y, cmap='brg')`
`plt.scatter(X_norm[:, 0], X_norm[:, 1], c=kmean_y_pred, cmap='brg')`
`plt.scatter(X_norm[:, 0], X_norm[:, 1], c=gmm_y_pred, cmap='brg')`

ご確認よろしくお願いいたします．

**Comment by shimitaku** [comment]
@tom-uchida 

ありがとうございます。
書籍執筆時点ではサンプルプログラムで図3.15（P.133）の結果が得られていたのですが、
いま実行してみると確かに色分けが異なりました。

ご指摘のとおり、
引数cに渡している各配列（`y`, `kmeans_y_pred`, `gmm_y_pred`）の値が影響しています。

各配列にはクラスタリング結果のラベル番号が格納されていますが、
scikit-learnが返すラベル番号の振り分けが執筆時点と異なっているようです。

たとえば、以下のようにラベル番号を入れ替えると図3.15（P.133）と同じ結果が得られます。

`plt.scatter(X_norm[:, 0], X_norm[:, 1], c=y, cmap='brg')`
`plt.scatter(X_norm[:, 0], X_norm[:, 1], c=2-kmeans_y_pred, cmap='brg')`
`plt.scatter(X_norm[:, 0], X_norm[:, 1], c=(gmm_y_pred+1) % 3, cmap='brg')`

なお、P.119の3〜6行目でも同様の解説をしていますが、
クラスタリング結果のラベルそのもの（つまりは色）には意味がないためラベル番号を入れ替えても問題はありません。

**Comment by tom-uchida** [comment]
ご返答ありがとうございます．

＞ scikit-learnが返すラベル番号の振り分けが執筆時点と異なっているようです。
なるほどです．

実は自分でも，ラベル番号を入れ替える処理を`np.where()`を使用して実装してみたのですが，
よりスマートな方法があるのではないかと気になったので，質問させていただきました．

ご提示いただいたコードであればインラインで済むので良さそうですね．

結局のところ，ラベル番号の問題ですので本質的ではないということですね．
解決しました．ご対応ありがとうございました．
